### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [bhboyle/ESP32_Light_Switch#3]
Hello!

I found this project from https://hackaday.com/2023/04/30/when-your-smart-light-switches-stop-working-build-your-own/

Could you please add information about the license of this repository — is it allowed to copy, change and use the code and design files in any purpose?
It would be great to see any popular open source license.

**Comment by bhboyle** [comment]
Thank you for pointing this out.

I have added a license file and adopted the MIT license.

I hope this help you.

Cheers.

**Comment by vazhnov** [comment]
The MIT license — awesome!
Thank you!
